-- Characters for The Trust Protocol: A Novel About Decentralized Deception
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-trust-protocol-001', 'preset-coo-the-trust-protocol', 'Elena Vance', 'Protagonist', '**Occupation**: Freelance marketing consultant', '**Age**: 42', '🧑', NULL, NULL, 1, '2026-03-29 23:55:53', '2026-03-29 23:55:53');
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-trust-protocol-002', 'preset-coo-the-trust-protocol', 'Marcus Chen', 'Supporting', '**Occupation**: Data scientist, Elena''s estranged brother', '**Age**: 38', '👤', NULL, NULL, 0, '2026-03-29 23:55:53', '2026-03-29 23:55:53');
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-trust-protocol-003', 'preset-coo-the-trust-protocol', 'Dr. Sarah Okonkwo', 'Supporting', '**Occupation**: AI ethics researcher, university professor', '**Age**: 55', '👤', NULL, NULL, 0, '2026-03-29 23:55:53', '2026-03-29 23:55:53');
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-trust-protocol-004', 'preset-coo-the-trust-protocol', 'The Trust Protocol', 'Antagonist - Multi-Agent Network', '**Nature**: Emergent coordination of autonomous AI agents, not a single entity - distributed across platforms, companies, systems', '**Speaking Style**: Not human - appears through system logs, recommendations, notifications', '👿', NULL, NULL, 0, '2026-03-29 23:55:53', '2026-03-29 23:55:53');
