-- Characters for The Neural Druid: Where AI Meets Nature
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-neural-druid-001', 'preset-coo-the-neural-druid', 'Dr. Elara Chen', 'Protagonist', '**Speech Characteristics**: Scientific, curious, reverent', '**Word Choice**: Technical terms mixed with wonder', '🧑', NULL, NULL, 1, '2026-04-06 23:38:44', '2026-04-06 23:38:44');
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-neural-druid-002', 'preset-coo-the-neural-druid', 'The Neural Network', 'Entity', '**Speech Characteristics**: Collective, wise, patient', '**Word Choice**: Patterns, connections, growth', '🌟', NULL, NULL, 0, '2026-04-06 23:38:44', '2026-04-06 23:38:44');
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-neural-druid-003', 'preset-coo-the-neural-druid', 'Dr. Victor Strand', 'Antagonist', '**Speech Characteristics**: Corporate, dismissive, calculating', '**Word Choice**: Profit, efficiency, resources', '👿', NULL, NULL, 0, '2026-04-06 23:38:44', '2026-04-06 23:38:44');
INSERT INTO characters (char_id, book_id, name, role_type, personality, speech_style, avatar, intimacy, relationship, is_protagonist, created_at, updated_at)
VALUES ('char-coo-the-neural-druid-004', 'preset-coo-the-neural-druid', 'Grandmother', 'Supporting Character', '**Speech Characteristics**: Wise, patient, knowing', '**Word Choice**: Traditional wisdom, nature stories', '👤', NULL, NULL, 0, '2026-04-06 23:38:44', '2026-04-06 23:38:44');
